package InterfaceOperationsApp;


/**
* InterfaceOperationsApp/InterfaceOperationsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Interface/InterfaceOperations.idl
* Sunday, February 19, 2023 6:40:16 PM EST
*/

abstract public class InterfaceOperationsHelper
{
  private static String  _id = "IDL:InterfaceOperationsApp/InterfaceOperations:1.0";

  public static void insert (org.omg.CORBA.Any a, InterfaceOperationsApp.InterfaceOperations that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static InterfaceOperationsApp.InterfaceOperations extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (InterfaceOperationsApp.InterfaceOperationsHelper.id (), "InterfaceOperations");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static InterfaceOperationsApp.InterfaceOperations read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_InterfaceOperationsStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, InterfaceOperationsApp.InterfaceOperations value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static InterfaceOperationsApp.InterfaceOperations narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof InterfaceOperationsApp.InterfaceOperations)
      return (InterfaceOperationsApp.InterfaceOperations)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      InterfaceOperationsApp._InterfaceOperationsStub stub = new InterfaceOperationsApp._InterfaceOperationsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static InterfaceOperationsApp.InterfaceOperations unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof InterfaceOperationsApp.InterfaceOperations)
      return (InterfaceOperationsApp.InterfaceOperations)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      InterfaceOperationsApp._InterfaceOperationsStub stub = new InterfaceOperationsApp._InterfaceOperationsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
