package InterfaceOperationsApp;

/**
* InterfaceOperationsApp/InterfaceOperationsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Interface/InterfaceOperations.idl
* Sunday, February 19, 2023 6:40:16 PM EST
*/

public final class InterfaceOperationsHolder implements org.omg.CORBA.portable.Streamable
{
  public InterfaceOperationsApp.InterfaceOperations value = null;

  public InterfaceOperationsHolder ()
  {
  }

  public InterfaceOperationsHolder (InterfaceOperationsApp.InterfaceOperations initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = InterfaceOperationsApp.InterfaceOperationsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    InterfaceOperationsApp.InterfaceOperationsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return InterfaceOperationsApp.InterfaceOperationsHelper.type ();
  }

}
