package InterfaceOperationsApp;


/**
* InterfaceOperationsApp/InterfaceOperationsPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Interface/InterfaceOperations.idl
* Sunday, February 19, 2023 6:40:16 PM EST
*/

public abstract class InterfaceOperationsPOA extends org.omg.PortableServer.Servant
 implements InterfaceOperationsApp.InterfaceOperationsOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("cancelMovieTickets", new java.lang.Integer (0));
    _methods.put ("addMovieSlots", new java.lang.Integer (1));
    _methods.put ("removeMovieSlots", new java.lang.Integer (2));
    _methods.put ("listMovieShowsAvailability", new java.lang.Integer (3));
    _methods.put ("bookMovieTickets", new java.lang.Integer (4));
    _methods.put ("getBookingSchedule", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // InterfaceOperationsApp/InterfaceOperations/cancelMovieTickets
       {
         String customerID = in.read_string ();
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         int numberOfTickets = in.read_long ();
         String $result = null;
         $result = this.cancelMovieTickets (customerID, movieID, movieName, numberOfTickets);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  /**
       * Permission Set - Admin Only.
       * This method add movie for particular movie if exist in hash map
       * and if the movie does not exist it will create a new movie entry.
       * @param movieId
       * @param movieName
       * @param bookingCapacity
       * @return string If operation successful or not
       */
       case 1:  // InterfaceOperationsApp/InterfaceOperations/addMovieSlots
       {
         String movieId = in.read_string ();
         String movieName = in.read_string ();
         int bookingCapacity = in.read_long ();
         String $result = null;
         $result = this.addMovieSlots (movieId, movieName, bookingCapacity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  /**
       * Permission Set - Admin Only.
       * This method removes the movie if existed.    
       * If movie show exist and customer has booked a ticket then
       * movie gets deleted and will book the same movie in next available slot for that customer.
       * @param movieId
       * @param movieName
       * @return string If operation successful or not
       */
       case 2:  // InterfaceOperationsApp/InterfaceOperations/removeMovieSlots
       {
         String movieId = in.read_string ();
         String movieName = in.read_string ();
         String $result = null;
         $result = this.removeMovieSlots (movieId, movieName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  /**
       * Permission Set - Admin Only.
       * This method shows the availability for a particular movie in all theaters.
       * @param movieName
       * @return string If operation successful or not
       */
       case 3:  // InterfaceOperationsApp/InterfaceOperations/listMovieShowsAvailability
       {
         String movieName = in.read_string ();
         String $result = null;
         $result = this.listMovieShowsAvailability (movieName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  /**
       * Permission Set - Admin and User.
       * This method is used tp book movie tickets.
       * @param customerID
       * @param movieId
       * @param movieName
       * @param numberOfTickets
       * @return string If operation successful or not
       */
       case 4:  // InterfaceOperationsApp/InterfaceOperations/bookMovieTickets
       {
         String customerID = in.read_string ();
         String movieId = in.read_string ();
         String movieName = in.read_string ();
         int numberOfTickets = in.read_long ();
         String $result = null;
         $result = this.bookMovieTickets (customerID, movieId, movieName, numberOfTickets);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  /**
       * Permission Set - Admin and User.
       * This method is used tp book movie tickets.
       * @param customerID
       * @return string If operation successful or not
       */
       case 5:  // InterfaceOperationsApp/InterfaceOperations/getBookingSchedule
       {
         String customerID = in.read_string ();
         String $result = null;
         $result = this.getBookingSchedule (customerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:InterfaceOperationsApp/InterfaceOperations:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public InterfaceOperations _this() 
  {
    return InterfaceOperationsHelper.narrow(
    super._this_object());
  }

  public InterfaceOperations _this(org.omg.CORBA.ORB orb) 
  {
    return InterfaceOperationsHelper.narrow(
    super._this_object(orb));
  }


} // class InterfaceOperationsPOA
