package InterfaceOperationsApp;


/**
* InterfaceOperationsApp/InterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Interface/InterfaceOperations.idl
* Sunday, February 19, 2023 6:40:16 PM EST
*/

public interface InterfaceOperations extends InterfaceOperationsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface InterfaceOperations
